# kubectl apply -f simple-pod.yml
# kubectl get pods
# kubectl port-forward pod/nginx 8080:80
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: dev
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
